<Project>
  <PropertyGroup>

    <!--Versioning-->
    <VersionPrefix>5.2.0</VersionPrefix>
    <VersionSuffix></VersionSuffix>

    <!-- Targets -->
    <LangVersion>10.0</LangVersion>

    <!--NuGet-->
    <Authors>Anthony Reilly &amp; Michelangelo Accettura III</Authors>
    <Copyright>2026 Anthony Reilly &amp; Michelangelo Accettura III</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/maccettura/NetCoreForce</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>salesforce,api,forcedotcom,netstandard,netcore</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/maccettura/NetCoreForce</RepositoryUrl>
    <PackageReleaseNotes>Release notes and documentation can be found on the project site: https://github.com/maccettura/NetCoreForce</PackageReleaseNotes>

    <!-- Intentionally targeting EOL frameworks -->
     <CheckEolTargetFramework>false</CheckEolTargetFramework>

    <!--Project Root-->
    <SolutionDir>$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), *.sln))</SolutionDir>
  </PropertyGroup>

  <PropertyGroup>
    <LibTargetFrameworks>net8.0;net9.0;net10.0</LibTargetFrameworks>
    <AppTargetFrameworks>net8.0;net9.0;net10.0</AppTargetFrameworks>
  </PropertyGroup>
</Project>