<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NetCoreForce.Client</AssemblyName>
    <Product>Maccettura.NetCoreForce.Client</Product>
    <OutputType>Library</OutputType>
    <TargetFrameworks>$(LibTargetFrameworks)</TargetFrameworks>

    <!--NuGet-->
    <Description>A .NET Standard and .NET Core Salesforce REST API integration library</Description>
    <IsPackable>true</IsPackable>
    <PackageId>Maccettura.NetCoreForce.Client</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <!-- warning CS1591: Missing XML comment for publicly visible type or member -->
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath>$(SolutionDir)/packages</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>